### ISSUE TITLE
protobufのversionに関するbug

### ISSUE THREAD

**Issue by nissymori** [mjx-project/mjx#1144]
昨日mergeした際に取り込んだupdateによって以下のbugが発生するようになりました.
<img width="1145" alt="スクリーンショット 2022-10-01 9 50 46" src="https://user-images.githubusercontent.com/55940613/193376610-8a01a322-6d3c-4fa3-a479-19dcfd97018f.png">

調べたろことversion周りのエラーっぽいです.
https://github.com/protocolbuffers/protobuf/issues/9778
https://ittutorialpoint.com/importerror-cannot-import-name-builder-from-google-protobuf-internal/

pipでprotobufのversionを変えていると以下のような警告が表示されます.
<img width="919" alt="スクリーンショット 2022-10-01 9 57 58" src="https://user-images.githubusercontent.com/55940613/193376901-3f3c4782-a0ec-4ebf-8762-19a058b5e241.png">

grpcio==1.49.1とprotobuf==3.17.3はrequirementsで指定されていますが, incompatibleなようです.

リンクにある解決法を試していきます.

**Comment by sacckey** [comment]
私の環境だと`pip install protobuf==3.20.0`で解決しました(警告は出ますが)。
grpcのversionを上げたときに気付けず申し訳ないです🙇‍♂️

**Comment by nissymori** [comment]
> pip install protobuf==3.20.0

ありがとうございます！私の環境でも同じ方法で解決しました！

**Comment by sotetsuk** [comment]
ご報告ありがとうございました 🙏 
遅くなりましたが対応しました 🙏
